### ISSUE TITLE
Make issues

### ISSUE THREAD

**Issue by bertbeck** [ohler55/agoo-c#1]
What is the correct procedure for building?

make in the root directory produces this:

bert@ubuntu-1:~/projects/agoo-c$ make
make -C src refresh
make[1]: Entering directory `/home/bert/projects/agoo-c/src'
mkdir -p agoo
echo "all:\n    make -C ..\n" > agoo/Makefile
cp ../../agoo/ext/agoo/atomic.h agoo
cp: cannot stat ‘../../agoo/ext/agoo/atomic.h’: No such file or directory
make[1]: *** [refresh] Error 1
make[1]: Leaving directory `/home/bert/projects/agoo-c/src'
make: *** [all] Error 2

**Comment by ohler55** [comment]
A simple make from the `src` directory should do it. Agoo-c uses code from the Agoo repo so that's what the make refresh does. I'll add some build instructions.

I'm curious, are you looking for a straight server or one that does GraphQL? Agoo-c was made initially to participate in benchmarks. I think I can get a bit more out of it performance-wise in the near future.

Anyway, if you are going to spend some time with it I am glad to improve it and add features.

**Comment by bertbeck** [comment]
hmmm. I did a make from src. Will try again but I'm pretty sure it couldn't
find some includes.

I'm just trying the simple example build. My goal is to find the fastest
simple web server to benchmark against my development efforts in crystal go
and rust. I can't get more that 2,000 request/seconds on my local mac, or
about 1700 rps on Digital Ocean and AWS small instances. Your benchmarks
seemed faster from a site I found on the web.

Are you doing selects/non blocking io on sockets? That seems to be the
answer for higher performance. Digital Ocean and AWS just have 1 core - so
multiple threads probably don't help.

Should I do a "make refresh" first?

Thanks

Bert

**Comment by bertbeck** [comment]
still no luck.

It looks like the makefile expects the project to be in the agoo directory
- but the git clone puts it in agoo-c

where does the ext directory come from?

I've tried building in both master and develop - git clone sets develop as
the current branch

Here's my results:

bert@ubuntu-1:~/projects/agoo-c$ cd src

bert@ubuntu-1:~/projects/agoo-c/src$ make refresh

mkdir -p agoo

echo "all:\n make -C ..\n" > agoo/Makefile

cp ../../agoo/ext/agoo/atomic.h agoo

cp: cannot stat ‘../../agoo/ext/agoo/atomic.h’: No such file or directory

make: *** [refresh] Error 1

bert@ubuntu-1:~/projects/agoo-c/src$ ls ../..

*agoo-c*         *nodeapp*                          *rust_ws*
*web-frameworks*

*agoo-c-save*    *nodehero-authentication*          *SinglePageApp*
*webserver_c*

*h2o*            npm-debug.log                    *skiapp*
*ws_crystal*

*haywire*        *OnTheSnow_ws*                     *snowflake*      *wslay*

*micro-service*  *onthesnow.zip*                    *sparkle*

*ngrest*         *react-universal-web-apps-simple*  *tabs*

bert@ubuntu-1:~/projects/agoo-c/src$ cd ..

bert@ubuntu-1:~/projects/agoo-c$ cd ..

bert@ubuntu-1:~/projects$ mv agoo-c agoo

bert@ubuntu-1:~/projects$ cd agoo

bert@ubuntu-1:~/projects/agoo$ cd src

bert@ubuntu-1:~/projects/agoo/src$ make refresh

mkdir -p agoo

echo "all:\n make -C ..\n" > agoo/Makefile

cp ../../agoo/ext/agoo/atomic.h agoo

cp: cannot stat ‘../../agoo/ext/agoo/atomic.h’: No such file or directory

make: *** [refresh] Error 1

bert@ubuntu-1:~/projects/agoo/src$ cd ..

bert@ubuntu-1:~/projects/agoo$ ls

CHANGELOG.md  *example*  *include*  *lib*  LICENSE  Makefile  README.md
*src*

bert@ubuntu-1:~/projects/agoo$

**Comment by ohler55** [comment]
Sorry, I can't get to the adding the docs and changes til this evening but here are the steps. (Don't do a `make refresh`. That's for me only. I'll make that step separate to avoid confusion.)

Start with fresh pull so all the files are there.

```
cd src
make
```
Then to try an example.
```
cd example/simple
make
```
The `simple` app should be ready to run.

**Comment by ohler55** [comment]
I pushed a better README.md and also changed the Makefile. Let me know it you are able to get the project and example to build. Thanks.

**Comment by bertbeck** [comment]
I finally got it to work - it needs a more current version of gcc. I had
4.7 running on ubuntu 14.04. I had to upgrade to gcc-7 to get stdatomic.h
to be included.

Interesting - I'm benchmarking various simple web services / micro services
on Digital Ocean, AWS and my Macbook pro - just responding to a "/" get
request and sending an empty response.
I'm only able to get < 2000 requests per second as benchmarked by wrk2.
Yours does 1633 rps. I've tried a libuv version as well and still always
under 2000 requests per second. I've run the same code on aws (micro
instance) and same results.

Did you do any benchmarking of your performance? I'm thinking that maybe
digital ocean and aws or comcast (my ISP) might be rate limiting - but
maybe not. I usually seem claims of 20K request per seconds - but I don't
see this.

I'd update your docs to note that you require a modern C11 compiler (or
gcc-7)

Bert

**Comment by ohler55** [comment]
Updated the README, thanks.

Some benchmarks for Agoo-C are [here](https://github.com/the-benchmarker/web-frameworks).

I suspect the slow results you are getting are due to the network. If you are testing on AWS then test both the web server and the benchmark tool on the AWS network. Make sure you have a decent bandwidth. If you are benchmarking across the internet don't expect good results as the network will be the bottleneck.

Some other things to consider. Make sure the connection is kept alive. With `wrk` that is the default. For something like my `perfer` use the `-k` option. Also many server support pipeline which allows multiple requests to be outstanding from the same client. For `perfer` that is the `-b` option.

I test on my laptop and easily get over 100,000 request per second.

**Comment by bertbeck** [comment]
Aha!

I see that in the wrk command there is a --rate parameter that was set to
2000. I took an example off the web.
When I set it to 20,000, throughput climbs to 20,000 for running local
It is still just 1640 rps running on Digital Ocean - maybe a bandwidth
limitation on Comcast or Digital Ocean. In the end - real world internet
requests per second is what I'm interested in. I've seen a few load testers
that spread out over the web - will give those a try.

Have you done any load testing with queries into a postgres database?

**Comment by bertbeck** [comment]
I'm getting about 70K rps running on my macbook (client and server running
on the same machine)

**Comment by ohler55** [comment]
I have not done any load testing with postgres. A bit with mongodb though. It is not very fast out of the box.

70K sounds about right for a macbook running macOS. Boot it into linux and you should see results that are 50% faster. macOS doesn't do very well with IO compared to linux.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by bertbeck** [comment]
Yes
