### ISSUE TITLE
great work! any benchmark against uwebsocket's http function?

### ISSUE THREAD

**Issue by superdolt** [ohler55/agoo-c#14]
great work! any benchmark against uwebsocket's http function?
just curious how it compares with uwebsocket's http
https://miro.medium.com/max/700/1*1MrkEKoWL7MnDYuY3dk8aA.png

**Comment by ohler55** [comment]
Not that I am aware of. Would you be interested in adding uwebsockets to https://github.com/the-benchmarker/graphql-benchmarks that would be great.
