### ISSUE TITLE
Route pattern support

### ISSUE THREAD

**Issue by hieunc229** [ohler55/agoo-c#2]
Hi Peter, I've been playing with agoo-c and think it's great. Since it didn't work when I try using regex pattern, how can I define dynamic routes?
For example: `/$project/users/$username`, where it can get `$project` and `$username`.

Thank you

**Comment by ohler55** [comment]
Take a look at `https://www.rubydoc.info/gems/agoo/2.8.3/Agoo/Server`, the `handle` method. It supports a glob pattern matching. "The path pattern follows glob like rules in that a single * matches a single token bounded by the `/` character and a double ** matches all remaining."

**Comment by hieunc229** [comment]
Ah alright, thank you :)
