### ISSUE TITLE
Discus on Agoo-C in other language

### ISSUE THREAD

**Issue by proyb6** [ohler55/agoo-c#3]
Can I reach you by email to get agoo-c adopt in other language?

**Comment by ohler55** [comment]
Sure, peter@ohler.com

What language are you interested in?

**Comment by proyb6** [comment]
V Language
https://vlang.io/

**Comment by ohler55** [comment]
Interesting. Let me look at the language a bit first. I might be able to do something.

**Comment by proyb6** [comment]
I have emailed you.

**Comment by s0kil** [comment]
Isn't V still too immature for this?

**Comment by proyb6** [comment]
@s0kil That’s the point, we could build something through the community driving force.
