### ISSUE TITLE
Simple demo guide please

### ISSUE THREAD

**Issue by dalisoft** [ohler55/agoo-c#9]
Hi @ohler55 

I didn't seen new release and see SSL support (which is great), but can't run demo.

## Steps
- `git clone https://github.com/ohler55/agoo-c.git`
- `cd agoo-c`
- `make`
- `cd examples/simple`
- `cd ssl`
- `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -nodes -days 365 -subj '/CN=localhost'`
- `cd ../`
- `make`
- `./simple`

## Directory
![](http://joxi.ru/12M3zy4SlaQZOr?d=1)

## Error
```bash
$ ./simple
Failed to bind to port 6464. https requires OpenSSL. Rebuild with OpenSSL. (127.0.0.1:6465)
```

## System
- macOS Sierra (10.12.6)
- bash v5

Everything looks good or something i'm missing?

Thanks

**Comment by ohler55** [comment]
Lets make sure you are building with SSL. Agoo-C tests for the existence of `/usr/local/opt/openssl/include/openssl/ssl.h` Is the header there?

I should add a README.md file with the steps. I will do that. Might be next week as I will be traveling this weekend.

**Comment by dalisoft** [comment]
Yes, that header here. I used just cloned and tried run

**Comment by ohler55** [comment]
From the error message it looks like Agoo-C was not build with SSL so that is the place to start. Along with the README.md I'll add some debugging to the Makefile and Agoo-C so it lets you know if SSL is supported after a build.

**Comment by dalisoft** [comment]
Thanks a lot for fast and well described response

**Comment by dalisoft** [comment]
As already able to run C code on my machine, issue solved
